### ISSUE TITLE
Track recent babel changes

### ISSUE THREAD

**Issue by aminophen** [texjporg/babel-japanese#3]
texjporg/texjporg.github.io#6 に関連して，babel-japanese のドキュメント冒頭に英語ドキュメントを整備中です。

現在の babel-japanese ドキュメントは「ひと昔前の babel の状態」をベースにした記述ですが，最近の babel の説明書を見ると，状況は変わってきているようです（試せていません）。

* 昔の babel だと「欧文クラスファイルのプレースホルダが \partname しかないので『第1部』のように挟む訳語を使えない」という制約がありました。
* しかし現在の babel のドキュメントを見ると，日本語やハンガリー語の語順サポートのために，機能拡張されているように見えます。

これがどのくらい実用可能か，改めて試してみたほうがよさそうです。

**Comment by aminophen** [comment]
From https://github.com/latex3/babel README.md:

```
3.48   2020-09-01
       - New (tentative) tools to customize some labels (like chapters in CJK and Hungarian).
```

babel.pdf v3.51 p.150:

> To show correctly some captions in a few languages, we need to patch some internal
> macros, because the order is hardcoded. For example, in Japanese the chapter number is
> surrounded by two string, while in Hungarian is placed after. These replacement works in
> many classes, but not all. Actually, the following lines are somewhat tentative.

**Comment by jbezos** [comment]
Feel free to make suggestions.

**Comment by aminophen** [comment]
@jbezos Thanks. Could you tell me how to define a custom chapter format in LaTeX? I'd like to make use of the new feature in babel v3.48 but cannot find any user interface to add a definition like \prechaptername\thechapter\postchaptername.

**Comment by jbezos** [comment]
Sorry for the late answer. This feature is currently available only with the mechanism of `ini` files, which is more or less under the direct control of `babel`. It must be extended to the old good `ldf`mechanism, which is more open and therefore I'd like to be careful and make sure it works under not so restricted conditions. As I explain in the readme, it should work with standard classes (it seems to work with a few others), but before making it available to `ldf' files a need know how it behaves in some others classes. The current code is somewhat hackish, and hacks are always dangerous.

**Comment by aminophen** [comment]
@jbezos Thanks for the explanation; if you are going to extend to the ldf mechanism, I'm willing to test it to see whether some strange things happen or not.

**Comment by aminophen** [comment]
I added a code based on latex3/babel#111.
