### ISSUE TITLE
作成中の新生 japanese.pdf に対するコメント

### ISSUE THREAD

**Issue by wtsnjp** [texjporg/babel-japanese#4]
気付いた点をつらつらと書いていきます．ほとんどが英語をちょっと直すだけのものですが（妥当でないと思われる指摘は捨て置いてください）．

### 冒頭部

- `\today → “December 1, 2020”` → `\today → “令和2年12月1日”`（この文書自体は `\usepackage[japanese]{babel}` でないので，出力文字列を直打ちする必要がありそうです）
- 2段落目後半は，この文書で “the minimum requirements” を定義するというように読めますが，その方向性がいいでしょうか？（詳細は後述します）

### 第1節

- `Using jlreq class` → `Using the jlreq class`
- `Save the above as jp1.tex and run a command` → `Save the above as jp1.tex and run the following command`
- `a Japanese font family “HaranoAji Mincho/Gothic”` → `the Japanese font family “HaranoAji Mincho/Gothic”`
- “Western” という語は日本人視点な気がするので，“classes not for Japanese typesetting” ぐらいの方がわかりやすいかも？

### 第2節

- `Save the above as jp2.tex and run a command.` → `Save the above as jp2.tex and run the following command.`
- `The output is always a DVI file.` → `Their outputs are always DVI files.`
- `If you have jp2.dvi, running a command.` → `If you have jp2.dvi, running the following`（ピリオドをトル）

### 第3節

- `before the publication of Unicode 1.0.` → `before the release of Unicode 1.0.`
- `pLaTeX only supports limited character set JIS X 0208 (6879 characters).` → `pLaTeX only supports a limited character set, JIS X 0208 (6879 characters).`
- `Save the above as jp3.tex and run a command.` → `Save the above as jp3.tex and run the following command.`
- `Again the DVI file can be converted into PDF using dvipdfmx.` → `Again, the DVI file can be converted into PDF by using dvipdfmx.`

### 第4節

この節の見出しは変えた方がいい気がしました．“minimal requirements for Japanese typesetting” というと，満たすべき項目が具体的に列挙された JLReq のサブセットのような「規定」のような印象を持ちます．予想ですが，海外開発者が見たらよりそういうものを想像しそうな気がします．しかし，私の理解では，この文書の目的はそのような「規定」を定義・策定したいということではないはずです．

この文書で目指したいのはむしろ「欧文組版を出発点として，和文組版を行うように改変するには，どのような変更が必要で，どんなことに注意しなければならないのか」のサマリーを提供することではないでしょうか．したがって，見出しも “A short summary of differences between English and Japanese typesetting” ぐらいにして，内容もその観点で語られるべきだと思います．

既に箇条書きで列挙されている項目は「欧文組版と和文組版の違い」に当たるものだけを選んで列挙されているようなので，それは特に変える必要がなくて，ただ書き方の問題ですかね．

### 第5節

- `There are some documentations in both English and Japanese.` → この文は不要な気がします（ちなみに documentation は不可算）

### 第6節

- `All the major frameworks for Japanese typesetting provide “standard class”` → `All the major frameworks for Japanese typesetting provide “standard classes”`

**Comment by wtsnjp** [comment]
あと，冒頭部の第2段落は全体を `\emph` で強調してもいいかもしれません．

**Comment by aminophen** [comment]
ありがとうございます。更新してみました → 34825a5

**Comment by h20y6m** [comment]
A.3 More typefaces

最初の例がLuaLaTeXなのにjlreq-deluxeを使ったものになっています。
（jlreq-deluxeは(u)pLaTeX用です）

**Comment by aminophen** [comment]
> 最初の例がLuaLaTeXなのにjlreq-deluxeを使ったものになっています。

ありがとうございます。直しました → 89f41c0
