### ISSUE TITLE
[japanese.pdf] xkanjiskip on XeTeX

### ISSUE THREAD

**Issue by minamotorin** [texjporg/babel-japanese#5]
Thanks for the useful and interesting document.

Footnote 5 on page 10 says
> pdfTeX and XeTeX cannot insert a quarter em space (shibu aki) automatically, so the active character `~` is redefined to a macro to insert it manually.

But as you can see from the code below, I don't think this is correct on XeTeX with standard japanese driver of bxjscls.
```latex
%#!xelatex
\documentclass[xelatex,ja=standard]{bxjsbook}
\begin{document}
\meaning~

こんにちは，日本語に少し~English~を含めてみます。

こんにちは，日本語に少し English を含めてみます。

こんにちは，日本語に少しEnglishを含めてみます。
\end{document}
```

**Comment by aminophen** [comment]
Thanks for your report: I'll adjust the sentence
